name: Build Windows EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install UPX compressor
      run: |
        Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-win64.zip" -OutFile "upx.zip"
        Expand-Archive -Path "upx.zip" -DestinationPath "upx_temp"
        Copy-Item "upx_temp\upx-4.2.2-win64\upx.exe" -Destination "upx.exe"

    - name: Install ALL Dependencies
      run: pip install pyinstaller pyside6 minecraft-launcher-lib requests

    - name: Build Client EXE (Slimmed Down)
      run: pyinstaller --onefile --windowed --name "UREEDXD_Client" --exclude-module PySide6.QtWebEngine --exclude-module PySide6.QtWebEngineWidgets --exclude-module PySide6.QtWebChannel --exclude-module PySide6.QtMultimedia --exclude-module PySide6.Qt3DCore --exclude-module PySide6.Qt3DRender --exclude-module PySide6.QtBluetooth --exclude-module PySide6.QtNfc --exclude-module PySide6.QtPositioning --exclude-module PySide6.QtSensors ureedxd_client.py

    - name: Build Setup EXE
      run: pyinstaller --onefile --windowed --icon=UREEDXD.ico --name "UREEDXD_Setup" --upx-dir=. main.py

    - name: Package into ZIP
      run: Compress-Archive -Path "dist\UREEDXD_Setup.exe", "dist\UREEDXD_Client.exe", "UREEDXD.ico" -DestinationPath "UREEDXD_Installer.zip"

    - name: Upload the Final ZIP
      uses: actions/upload-artifact@v4
      with:
        name: UREEDXD_Installer
        path: UREEDXD_Installer.zip
