name: Build Windows EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install UPX compressor
      run: |
        Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-win64.zip" -OutFile "upx.zip"
        Expand-Archive -Path "upx.zip" -DestinationPath "upx_temp"
        Copy-Item "upx_temp\upx-4.2.2-win64\upx.exe" -Destination "upx.exe"

    - name: Install ALL Dependencies
      run: pip install pyinstaller pyside6 minecraft-launcher-lib requests

    - name: Build Client EXE
      run: pyinstaller --onefile --windowed --name "UREEDXD_Client" ureedxd_client.py

    - name: Build Setup EXE (with Client hidden inside)
      run: pyinstaller --onefile --windowed --icon=UREEDXD.ico --name "UREEDXD_Setup" --add-data "UREEDXD.ico;." --add-data "dist/UREEDXD_Client.exe;." --upx-dir=. main.py

    - name: Upload the Final Setup
      uses: actions/upload-artifact@v4
      with:
        name: UREEDXD_Installer
        path: dist\UREEDXD_Setup.exe
